### ISSUE TITLE
stacks_signMessage crash the xverse app when passed a ClarityValue instead of a string message

### ISSUE THREAD

**Issue by zhigang1992** [secretkeylabs/wallet-connect#11]
We would like to be able to sign a structured data in the format of ClarityValue. But the current implementation of stacks_signMessage seems to only support a string message.

**Comment by abdulhaseeb4239** [comment]
closing this issue as this is resolved in mobile app release [1.18.3](https://github.com/secretkeylabs/xverse/releases/tag/v1.18.3)
