### ISSUE TITLE
stacks_contractCall support for sponsored Tx

### ISSUE THREAD

**Issue by zhigang1992** [secretkeylabs/wallet-connect#12]
Currently there is no way to create a sponsored tx when integrated via WalletConnect.

**Comment by abdulhaseeb4239** [comment]
The support for sponsored transactions has been introduced in version [1.18.3](https://github.com/secretkeylabs/xverse/releases/tag/v1.18.3) of Xverse app, Also, the relevant example is added in [webapp](https://github.com/secretkeylabs/wallet-connect/pull/13/files)
